### PR TITLE
Added skype symbol to socials

### PR DESCRIPTION
**Pull request by enricodangelo**
Hi, I just added the skype icon to the socials collection for all iconsets (awesome, marvosym and letters).
I think I respected your code standards.

### CODE REVIEW

**Comment by qin-nz** [comment]
hi @enricodangelo , can you tell me how to generate code for `moderncviconsmarvosym.sty`

**Comment by enricodangelo** [comment]
@qin-nz I don't know, I found that on the web, sorry.

**Comment by xdanaux** [comment]
Thanks Enrico. Could you please add a line to template.tex to show how one would use this new feature? Thanks!

**Comment by enricodangelo** [comment]
Hi xdanaux, I added the example in template.tex and template-multibib.tex, recompiled template-multibib.pdf and merged the new changes in master.

**Comment by xdanaux** [comment]
Thanks!

**Pull request merged**
