### PR TITLE
add gitlab social link

### PR DESCRIPTION
**Pull request by tjaartvdwalt**
Hi, 
I added Gitlab as a social link.
Not sure if this is useful, but I thought I would send a pull request and let you decide.
This only works if you are using the `awesome` icon set. Maybe someone can help me to get it into `marvosym`

### CODE REVIEW

**Comment by FranklinYu** [comment]
Note: the logo [`\faGitlab`](http://fontawesome.io/icon/gitlab/) requires [v4.6 of package `fontawesome`](https://github.com/FortAwesome/Font-Awesome/releases/tag/v4.6.0) which came out this April. For example, I met problem when I was using TeX Live 2015 (which obviously does not include this version of `fontawesome`); using TeX Live 2016 solved it.

If anyone wants GitLab link before this pull request is merged, try the workaround mentioned in #12.

**Comment by tjaartvdwalt** [comment]
@franklinyu, thank you for sharing this.

Unless someone objects I will consider abandoning the pull request, since:
- The solution in #12 is more generic than my solution.
- There has been no feedback to any pull requests recently, so it looks unlikely that it will be merged.

**Comment by xdanaux** [comment]
Could you please add a line in moderncviconsmarvosym.sty?
Just
\newcommand*{\gitlabsocialsymbol}{}
so that I don't lose track of this icon?

Thanks!

**Comment by xdanaux** [comment]
This was merged with commit 2033517d3f29f9c16af1b3421d52f281e94aa2a5

**Pull request closed without merging**
